basePath: /
host: www.alive.org.tw
info:
  contact:
    email: rayselfs@alive.org.tw
    name: API Support
    url: https://github.com/your-repo
  description: This is a sample server for a Bible API system, powered by Gin and
    GORM.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Bible System API
  version: "1.0"
paths: {}
schemes:
- https
swagger: "2.0"
